### ISSUE TITLE
Problems with integration in TYPO3 11.5

### ISSUE THREAD

**Issue by Kephson** [r3h6/TYPO3.EXT.oidc_server#5]
Hello @r3h6 ,
I'm trying to integrate an OpenID connect server with your EXT in a TYPO3 11.5 project but it fails because of missing documentation.
Is there any other documentation on how I could get it work in my project?

Could I help to update the project documentation? Did I miss any docs?

Thanks in advance.

**Comment by r3h6** [comment]
If you read the oauth2_server docs too, then you did not miss any docs.
Help improving code or docs is always welcome.

**Comment by Kephson** [comment]
Ok, I used this documentation, too.
I will try to handle it by my own with debugging the problems.

**Comment by r3h6** [comment]
Could you solve your issue?

**Comment by Kephson** [comment]
Hi, I'm still working on it and will report if this could be closed.
