### ISSUE TITLE
TYPO3 Core patch necessary?

### ISSUE THREAD

**Issue by infabo** [r3h6/TYPO3.EXT.oidc_server#8]
Hi!

There is a patch declared in composer.json:

https://github.com/r3h6/TYPO3.EXT.oidc_server/blob/master/composer.json#L66

Is this patch mandatory? It fails to apply with `cweagans/composer-patches` in version 1.7.3.

![image](https://github.com/user-attachments/assets/8c0ea6c4-37a5-412c-9c0a-672a1d0b28b9)

I have enabled patching in my project's composer.json because I need that functionality on other packages as well:

```
"extra": {
		"enable-patching": true,
		"patches": {
		},
		"patches-ignore": {
			"r3h6/oidc-server": {
				"typo3/cms-core": {
					"Fix path issue": "Build/Patches/package-path.diff"
				}
			}
		}
	}
```

To work around the issue I have ignored the patch provided by this package.

**Comment by r3h6** [comment]
@infabo This patch is rather a left over from development, I will check it
